I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 48, in script
    with none
  File "game/script.rpy", line 48, in <module>
    with none
NameError: name 'none' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 48, in script
    with none
  File "C:\Users\Alexander\Documents\GitHub\Kirei-Git\renpy\ast.py", line 1180, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\Users\Alexander\Documents\GitHub\Kirei-Git\renpy\python.py", line 1416, in py_eval
    return eval(py_compile(source, 'eval'), globals, locals)
  File "game/script.rpy", line 48, in <module>
    with none
NameError: name 'none' is not defined

Windows-post2008Server-6.2.9200
Ren'Py 6.17.6.512
Pretty 1.0
